require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConversionsController do

  # This should return the minimal set of attributes required to create a valid
  # Conversion. As you add validations to Conversion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConversionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all conversions as @conversions" do
      conversion = Conversion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conversions).should eq([conversion])
    end
  end

  describe "GET show" do
    it "assigns the requested conversion as @conversion" do
      conversion = Conversion.create! valid_attributes
      get :show, {:id => conversion.to_param}, valid_session
      assigns(:conversion).should eq(conversion)
    end
  end

  describe "GET new" do
    it "assigns a new conversion as @conversion" do
      get :new, {}, valid_session
      assigns(:conversion).should be_a_new(Conversion)
    end
  end

  describe "GET edit" do
    it "assigns the requested conversion as @conversion" do
      conversion = Conversion.create! valid_attributes
      get :edit, {:id => conversion.to_param}, valid_session
      assigns(:conversion).should eq(conversion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Conversion" do
        expect {
          post :create, {:conversion => valid_attributes}, valid_session
        }.to change(Conversion, :count).by(1)
      end

      it "assigns a newly created conversion as @conversion" do
        post :create, {:conversion => valid_attributes}, valid_session
        assigns(:conversion).should be_a(Conversion)
        assigns(:conversion).should be_persisted
      end

      it "redirects to the created conversion" do
        post :create, {:conversion => valid_attributes}, valid_session
        response.should redirect_to(Conversion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conversion as @conversion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conversion.any_instance.stub(:save).and_return(false)
        post :create, {:conversion => {}}, valid_session
        assigns(:conversion).should be_a_new(Conversion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conversion.any_instance.stub(:save).and_return(false)
        post :create, {:conversion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conversion" do
        conversion = Conversion.create! valid_attributes
        # Assuming there are no other conversions in the database, this
        # specifies that the Conversion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Conversion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => conversion.to_param, :conversion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested conversion as @conversion" do
        conversion = Conversion.create! valid_attributes
        put :update, {:id => conversion.to_param, :conversion => valid_attributes}, valid_session
        assigns(:conversion).should eq(conversion)
      end

      it "redirects to the conversion" do
        conversion = Conversion.create! valid_attributes
        put :update, {:id => conversion.to_param, :conversion => valid_attributes}, valid_session
        response.should redirect_to(conversion)
      end
    end

    describe "with invalid params" do
      it "assigns the conversion as @conversion" do
        conversion = Conversion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conversion.any_instance.stub(:save).and_return(false)
        put :update, {:id => conversion.to_param, :conversion => {}}, valid_session
        assigns(:conversion).should eq(conversion)
      end

      it "re-renders the 'edit' template" do
        conversion = Conversion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conversion.any_instance.stub(:save).and_return(false)
        put :update, {:id => conversion.to_param, :conversion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conversion" do
      conversion = Conversion.create! valid_attributes
      expect {
        delete :destroy, {:id => conversion.to_param}, valid_session
      }.to change(Conversion, :count).by(-1)
    end

    it "redirects to the conversions list" do
      conversion = Conversion.create! valid_attributes
      delete :destroy, {:id => conversion.to_param}, valid_session
      response.should redirect_to(conversions_url)
    end
  end

end
