require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrowsersController do

  # This should return the minimal set of attributes required to create a valid
  # Browser. As you add validations to Browser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrowsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all browsers as @browsers" do
      browser = Browser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:browsers).should eq([browser])
    end
  end

  describe "GET show" do
    it "assigns the requested browser as @browser" do
      browser = Browser.create! valid_attributes
      get :show, {:id => browser.to_param}, valid_session
      assigns(:browser).should eq(browser)
    end
  end

  describe "GET new" do
    it "assigns a new browser as @browser" do
      get :new, {}, valid_session
      assigns(:browser).should be_a_new(Browser)
    end
  end

  describe "GET edit" do
    it "assigns the requested browser as @browser" do
      browser = Browser.create! valid_attributes
      get :edit, {:id => browser.to_param}, valid_session
      assigns(:browser).should eq(browser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Browser" do
        expect {
          post :create, {:browser => valid_attributes}, valid_session
        }.to change(Browser, :count).by(1)
      end

      it "assigns a newly created browser as @browser" do
        post :create, {:browser => valid_attributes}, valid_session
        assigns(:browser).should be_a(Browser)
        assigns(:browser).should be_persisted
      end

      it "redirects to the created browser" do
        post :create, {:browser => valid_attributes}, valid_session
        response.should redirect_to(Browser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved browser as @browser" do
        # Trigger the behavior that occurs when invalid params are submitted
        Browser.any_instance.stub(:save).and_return(false)
        post :create, {:browser => {}}, valid_session
        assigns(:browser).should be_a_new(Browser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Browser.any_instance.stub(:save).and_return(false)
        post :create, {:browser => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested browser" do
        browser = Browser.create! valid_attributes
        # Assuming there are no other browsers in the database, this
        # specifies that the Browser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Browser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => browser.to_param, :browser => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested browser as @browser" do
        browser = Browser.create! valid_attributes
        put :update, {:id => browser.to_param, :browser => valid_attributes}, valid_session
        assigns(:browser).should eq(browser)
      end

      it "redirects to the browser" do
        browser = Browser.create! valid_attributes
        put :update, {:id => browser.to_param, :browser => valid_attributes}, valid_session
        response.should redirect_to(browser)
      end
    end

    describe "with invalid params" do
      it "assigns the browser as @browser" do
        browser = Browser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Browser.any_instance.stub(:save).and_return(false)
        put :update, {:id => browser.to_param, :browser => {}}, valid_session
        assigns(:browser).should eq(browser)
      end

      it "re-renders the 'edit' template" do
        browser = Browser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Browser.any_instance.stub(:save).and_return(false)
        put :update, {:id => browser.to_param, :browser => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested browser" do
      browser = Browser.create! valid_attributes
      expect {
        delete :destroy, {:id => browser.to_param}, valid_session
      }.to change(Browser, :count).by(-1)
    end

    it "redirects to the browsers list" do
      browser = Browser.create! valid_attributes
      delete :destroy, {:id => browser.to_param}, valid_session
      response.should redirect_to(browsers_url)
    end
  end

end
