require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FormsController do

  # This should return the minimal set of attributes required to create a valid
  # Form. As you add validations to Form, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "address" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormsController. Be sure to keep this updated too.
  def valid_session
    {}
  end
  
  describe "GET index", 'is not in use' do
    it "assigns all forms as @forms" do
      expect {
        get :index, {}, valid_session
      }.to raise_error(ActionController::RoutingError)
    end
  end

  describe "GET show", 'is not in use' do
    it "assigns the requested form as @form" do
      expect {
        get :show, {}, valid_session
      }.to raise_error(ActionController::RoutingError)
    end
  end

  describe "GET new" do
    it "assigns a new form as @form" do
      get :new, {}, valid_session
      assigns(:form).should be_a_new(Form)
    end
  end

  describe "GET edit" do
    it "assigns the requested form as @form" do
      expect {
        get :edit, {}, valid_session
      }.to raise_error(ActionController::RoutingError)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Form" do
        expect {
          post :create, {:form => valid_attributes}, valid_session
        }.to change(Form, :count).by(1)
      end

      it "assigns a newly created form as @form" do
        post :create, {:form => valid_attributes}, valid_session
        assigns(:form).should be_a(Form)
        assigns(:form).should be_persisted
      end

      it "redirects to the created form" do
        post :create, {:form => valid_attributes}, valid_session
        response.should redirect_to('/form/thank_you')
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved form as @form" do
        # Trigger the behavior that occurs when invalid params are submitted
        Form.any_instance.stub(:save).and_return(false)
        post :create, {:form => { "address" => "invalid value" }}, valid_session
        assigns(:form).should be_a_new(Form)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Form.any_instance.stub(:save).and_return(false)
        post :create, {:form => { "address" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update", 'is not in use' do
    describe "with valid params" do
      it "updates the requested form" do
        expect {
          put :update, {}, valid_session
        }.to raise_error(ActionController::RoutingError)
      end
    end
  end

  describe "DELETE destroy", 'is not in use' do
    it "destroys the requested form" do
      expect {
        delete :destroy, {}, valid_session
      }.to raise_error(ActionController::RoutingError)
    end
  end

end
