require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RedirectionController do

  # This should return the minimal set of attributes required to create a valid
  # Redirect. As you add validations to Redirect, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {code: 'test1', is_default: true, medium_id: nil, target_id: nil}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RedirectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all redirections as @redirections" do
      redirection = Redirection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:redirections).should eq([redirection])
    end
  end

  describe "GET show" do
    it "assigns the requested redirection as @redirection" do
      redirection = Redirection.create! valid_attributes
      get :show, {:id => redirect.to_param}, valid_session
      assigns(:redirection).should eq(redirection)
    end
  end

  describe "GET new" do
    it "assigns a new redirection as @redirection" do
      get :new, {}, valid_session
      assigns(:redirection).should be_a_new(Redirect)
    end
  end

  describe "GET edit" do
    it "assigns the requested redirection as @redirection" do
      redirection = Redirection.create! valid_attributes
      get :edit, {:id => redirection.to_param}, valid_session
      assigns(:redirection).should eq(redirection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Redirection" do
        expect {
          post :create, {:redirection => valid_attributes}, valid_session
        }.to change(Redirection, :count).by(1)
      end

      it "assigns a newly created redirection as @redirection" do
        post :create, {:redirection => valid_attributes}, valid_session
        assigns(:redirection).should be_a(Redirection)
        assigns(:redirection).should be_persisted
      end

      it "redirects to the created redirection" do
        post :create, {:redirection => valid_attributes}, valid_session
        response.should redirect_to(Redirection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved redirection as @redirection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Redirection.any_instance.stub(:save).and_return(false)
        post :create, {:redirection => {}}, valid_session
        assigns(:redirection).should be_a_new(Redirect)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Redirection.any_instance.stub(:save).and_return(false)
        post :create, {:redirection => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested redirection" do
        redirection = Redirection.create! valid_attributes
        # Assuming there are no other redirects in the database, this
        # specifies that the Redirect created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Redirection.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => redirection.to_param, :redirection => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested redirection as @redirection" do
        redirection = Redirection.create! valid_attributes
        put :update, {:id => redirection.to_param, :redirection => valid_attributes}, valid_session
        assigns(:redirect).should eq(redirection)
      end

      it "redirects to the redirect" do
        redirect = Redirect.create! valid_attributes
        put :update, {:id => redirect.to_param, :redirect => valid_attributes}, valid_session
        response.should redirect_to(redirect)
      end
    end

    describe "with invalid params" do
      it "assigns the redirectin as @redirectin" do
        redirection = Redirection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Redirection.any_instance.stub(:save).and_return(false)
        put :update, {:id => redirection.to_param, :redirection => {}}, valid_session
        assigns(:redirection).should eq(redirection)
      end

      it "re-renders the 'edit' template" do
        redirection = Redirection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Redirection.any_instance.stub(:save).and_return(false)
        put :update, {:id => redirection.to_param, :redirection => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested redirection" do
      redirection = Redirection.create! valid_attributes
      expect {
        delete :destroy, {:id => redirection.to_param}, valid_session
      }.to change(Redirect, :count).by(-1)
    end

    it "redirects to the redirections list" do
      redirection = Redirection.create! valid_attributes
      delete :destroy, {:id => redirection.to_param}, valid_session
      response.should redirect_to(redirects_url)
    end
  end

end
